github: [illvart]
patreon: illvart
ko_fi: illvart
custom: ["https://paypal.me/illvart", "https://buymeacoff.ee/illvart", "https://saweria.co/illvart", "https://trakteer.id/illvart", "https://link.dana.id/qr/yi8037z", "https://wsa.wallet.airpay.co.id/qr/005330a1bf44b977b83f"]
